// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc3550.Julius2018.commands;

import org.usfirst.frc3550.Julius2018.Robot;
import org.usfirst.frc3550.Julius2018.util.FieldMesures;

//import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.CommandGroup;

//public final float INCHES2MM = 25.4;

/**
 *
 */
public class Pos2ColorLeftObjCubeBascule1Command extends CommandGroup {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    
    public Pos2ColorLeftObjCubeBascule1Command() {
//    	addSequential(new AutoDriveDistanceCommand(30,  1)); // 0:Backward / 1:Forward
//    	addSequential(new AutoDriveRotateCommand(90, 0));    // 0:Left     / 1:Right
//    	addSequential(new AutoDriveDistanceCommand(45, 1)); // 0:Backward / 1:Forward
//    	addSequential(new AutoDriveRotateCommand(90, 1));    // 0:Left     / 1:Right
//    	addSequential(new AutoDriveDistanceTimedCommand(65,  1, 3)); // 0:Backward / 1:Forward// time
    	addSequential(new AutoDriveDistanceCommand(FieldMesures.P2L_LengthOne,  1)); // 0:Backward / 1:Forward
    	addSequential(new AutoDriveRotateCommand(FieldMesures.ROTATEANGLE, 0));    // 0:Left     / 1:Right
    	addSequential(new AutoDriveDistanceCommand(FieldMesures.P2L_LengthTwo, 1)); // 0:Backward / 1:Forward
    	addSequential(new AutoDriveRotateCommand(FieldMesures.ROTATEANGLE, 1));    // 0:Left     / 1:Right
    	addSequential(new AutoDriveDistanceTimedCommand(FieldMesures.P2L_LengthThree,  1, 3)); // 0:Backward / 1:Forward// time
    	addSequential(new DropCubeCommand());

    	//addSequential(new OuvrePince());
    }

}
